name: Main

on:
  - push
  - pull_request

jobs:
  main:

    strategy:
      matrix:
        python-version: ['3.11']
        os: ['ubuntu-22.04', 'macos-12', 'windows-2022']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-os:${{ matrix.os }}-python:${{ matrix.python-version }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        shell: bash
        run: pip3 install -r requirements.txt -r requirements-dev.txt

      - name: Check Python Version Compatibility
        shell: bash
        run: vermin --no-tips --no-parse-comments --target=3.8- --violations sharkclipper

      # Create a release for this OS (but only on a single version of Python).
      # See: https://github.com/Nuitka/Nuitka?tab=readme-ov-file#use-case-7--building-with-github-workflows

      - name: Fetch FFmpeg
        if: matrix.python-version == '3.11'
        shell: bash
        run: ./scripts/fetch-ffmpeg.py

      - name: Build ${{ runner.os }} Release Executable with Nuitka
        if: matrix.python-version == '3.11'
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: sharkclipper/cli/server.py
          standalone: true
          onefile: true
          output-file: 'shark-clipper-${{ runner.os }}-${{ RUNNER_ARCH }}'
          include-data-dir: |
            ./static=static
          include-data-files: |
            ./pyproject.toml=./
            ./ffmpeg=./
            ./ffprobe=./
          include-package: |
            sharkclipper

      - name: Upload Artifacts
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: 'shark-clipper-${{ runner.os }}-${{ RUNNER_ARCH }}'
          compression-level: 0
          path: build/shark-clipper*

      - name: Release Latest
        if: matrix.python-version == '3.11'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-release
          make_latest: true
          files: build/shark-clipper*

      - name: Cleanup
        if: matrix.python-version == '3.11'
        shell: bash
        run: rm -rf ffmpeg ffprobe build
